name: USE-DOCKER-FILE-WORKFLOW
on: push
jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Create-Docker-Image
        uses: docker/build-push-action@v2 
        with:
          context: .
          file: Dockerfile
          push: false
      container:  
        image: IMAGE_NAME:built
      - name: Checkout-Code
        uses: actions/checkout@v3
      - name: Start-Server
        run: npm start
